### ISSUE TITLE
Crash while using with swift 3.0

### ISSUE THREAD

**Issue by deepakarora-ios** [karnett/CalendarPicker#2]
Hello,

I implemented EPCalendarpicker in one of my app while i try to show calendar app is crash on numberOfItemsInSection method in EPCalendarPicker class.
can anyone please help me?

Thanks 
Deepak Arora.

**Comment by karnett** [comment]
Hi Deepak, could you please post the code you are using to open the calendar?
I'll see what I can do.

**Comment by deepakarora-ios** [comment]
Hello Kim , thanks for the revert . But i resolved the issues. Now i face
new problem i want to navigate from EPCalenarpicker.swift class (from pods)
to one of my .swift class.

With regards,
Deepak.

Thanks and Regards,
Deepak Arora
iOS Developer
AblySoft Pvt. Ltd.
